### ISSUE TITLE
嗨,请问有action或云函数的打算吗？

### ISSUE THREAD

**Issue by wuyan-git** [wangwangit/python_sign#11]

**Comment by wangwangit** [comment]
这个主要是我自用的一些脚本分享,可能后面有精力会做,你有兴趣一起维护么!

**Comment by wuyan-git** [comment]
我水平有限，正研究你的脚本呢。
刚开始学习Python

我的TG是wuyan_git，有什么小事儿，我尽力帮忙吧。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangwangit/python_sign"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangwangit/python_sign] 嗨,请问有action或云函数的打算吗？ (#11)





 
这个主要是我自用的一些脚本分享,可能后面有精力会做,你有兴趣一起维护么!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangwangit** [comment]
我也是前段时间学的python,我是做java的.
