### ISSUE TITLE
GLaDOS网站签到，TG提示“没有权限”

### ISSUE THREAD

**Issue by 17huiwei** [wangwangit/python_sign#4]
另外，https://glados.rocks/console/notification 里面对于访问来源IP是不是分海内和国内服务器？国内是glados.rocks，国外是glados.network。

**Comment by 17huiwei** [comment]
还是提示

GLaDOS梯子签到 : 

没有权限

**Comment by wangwangit** [comment]
没有权限可以看下是不是cookie不正确,或者按你说的,替换下请求的网址.
